platform: linux
image_resource:
  type: registry-image
  source:
    repository: node
    tag:
      "12.16.1"
inputs: 
  - name: code
outputs: 
  - name: code
run:
  path: code/ci/scripts/install-and-test.sh