platform: linux
image_resource:
  type: registry-image
  source:
    repository: node
    tag:
      latest
inputs: 
  - name: printhellowworld
outputs: 
  - name: printhellowworld
run:
  path: printhellowworld/ci/scripts/install-and-test.sh